platform :ios, '7.0'
pod 'CRGradientNavigationBar', '~> 0.3.2'
pod 'HexColors', '~> 2.2.1'
pod 'TSMessages', '~> 0.9.6'
pod 'VTAcknowledgementsViewController', '~> 0.10'
pod 'FMDB', '~> 2.2'
pod 'libextobjc', '~> 0.4'
pod 'SVProgressHUD', '~> 1.0'
pod 'MagicalRecord', '~> 2.2'
pod 'Mantle', '~> 1.4.1'
pod 'HockeySDK', '~> 3.5.4'
pod 'Masonry', '~> 0.4.0'
pod 'M13ProgressSuite', '~> 1.0.1'
pod 'MFFadeBackModalAnimation', '~> 0.0.1'
